# Generated by Django 5.0.6 on 2024-07-26 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_timetableclass_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetableclass",
            name="classnumber",
        ),
    ]
